### ISSUE TITLE
display/handling of non ascii-characters

### ISSUE THREAD

**Issue by thefoster** [irdvo/qexiv#1]
After compiling, the program doesn't show non ascii-characters (ö/ü/ä/ß etc) in the exif data.
I'm petty sure darktable wrote the metadata to the images (i tested this with) in utf-8.
Is there a possibility to fix this?
![screenshot_20170417_212324](https://cloud.githubusercontent.com/assets/27131763/25101396/6dc5ade0-23b4-11e7-8eb3-e05843c73ddb.png)

**Comment by irdvo** [comment]
Okee, I will look at it.

**Comment by irdvo** [comment]
This bug is fixed.

**Comment by thefoster** [comment]
thanks for that fast response

**Comment by thefoster** [comment]
is it planned to enable qexiv writing other tags than description and geodata?

**Comment by irdvo** [comment]
For me the description and geodata are the most important. Do you have any
suggestion for other tags ?

2017-04-22 21:31 GMT+02:00 thefoster <notifications@github.com>:

**Comment by thefoster** [comment]
Hello Dick,

I found qexiv when looking for a good mass tagger and was wondering that even 
some of the bigger players couldn't handle exif natively.
So basically i'd like to be able to edit all of the tags though for many it 
doesn't make sense.
But indeed some are interesting, Artist, Copyright, and rating as some 
software doesn't handle these fields correctly (e.g. Within Umlauts).
Another example is ProcessingSoftware, as for example photini seems to write 
that field although it hasn't done anything else on the image.

Am Sonntag, 23. April 2017, 23:21:47 CEST schrieb Dick van Oudheusden:
